### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mwarman** [mwarman/ionic8-playground#72]
### Description

Add internationalization with translation support. Add translations for spanish and french.

See: [`react-i18next`](https://www.npmjs.com/package/react-i18next).

**Comment by leotarditi** [comment]
I'm interested in taking on this task.

**Comment by mwarman** [comment]
@leotarditi Thank you for your interest. This is sort of my own personal playground project and I am not seeking contributions. I use this projects to teach myself these concepts.

Feel free to fork the project and work on these items. Again, thank you.
